PlaylistMaker 5.0
RomanKalin27/PlaylistMaker pull request #4
Opened 2023-04-20 20:18 UTC by RomanKalin27

Попытался реализовать room, без особых успехов. В итоге сделал через преференсы.

2023-04-21 18:15 UTC, NoDopezzz requested changes
В **pull request** оставил несколько комментариев:

- Комментарии с эмодзи `⚠️` являются критическими, их исправление обязательно для сдачи работы.
- Комментарии с эмодзи `⏫` носят рекомендательных характер, исправление их необязательно, но оно поможет тебе улучшить качество кода.
- Комментарии с эмодзи `👍` обозначают похвалу за изящное решение.
- Под комментариями с эмодзи `💡` обычно оставляю полезную дополнительную информацию, которая по-моему мнению может оказаться полезной.

2023-04-21 18:15 UTC, NoDopezzz commented on app/src/main/java/com/practicum/playlistmaker/TrackAdapter.kt
> +            if (App.historyList.size >= 10) {
⏫ Такие "магические" числа лучше сохранять в константы - в companion object или просто object. Имена переменных дают больше информации о них и при будет проще изменять их значение при необходимости

2023-04-21 18:15 UTC, NoDopezzz commented on app/src/main/java/com/practicum/playlistmaker/TrackAdapter.kt
> +        }
⏫ Строка `HistoryAdapter().notifyItemInserted(0)`
создает новый объект класса `HistoryAdapter` и сообщает о том, что в него добавился первый элемент.
У этого вызова не будет эффекта на текущий список элементов в истории, т.к. для этого нужно ссылаться на уже созданный адаптер. Кроме того, вызов метода `notifyItemInserted` сообщает адаптеру, что в него добавился первый элемент, но результатом обработки списка треков может быть не только такой. Также мы можем удалить последний элемент, если достигнем лимита в 10 треков в истории.

2023-04-21 18:15 UTC, NoDopezzz commented on app/src/main/res/drawable-night/ic_placeholder.xml
> +    <path android:fillColor="@android:color/white" android:pathData="M19.07,4.93l-1.41,1.41C19.1,7.79 20,9.79 20,12c0,4.42 -3.58,8 -8,8s-8,-3.58 -8,-8c0,-4.08 3.05,-7.44 7,-7.93v2.02C8.16,6.57 6,9.03
⏫ Цвета в векторных изображениях также можно выносить в файл ресурсов. Так, можно организовать более гибкую дизайн-систему приложения.
Кроме того, это поможет экономить занимаемое ресурсами место, если нам нужно иметь иконки разных цветов для разных тем приложения. Ведь вместо того, чтобы создавать две иконки и класть в `drawable` и `drawable-night`, мы можем создать одну иконку в `drawable`, а файл ресурса с цветом будет задан в `values` и `values-night`

2023-04-21 18:15 UTC, NoDopezzz commented on app/src/main/java/com/practicum/playlistmaker/SearchActivity.kt
> +                deleteBtn.isGone = searchEditText.text.toString().trim().isEmpty()
⏫ Операция `notifyDataSetChanged` является достаточно сложной, т.к. вызывает обновление всех элементов списка. Стоит пользоваться ей разумно и избегать частых вызовов и обновлять список только в том случае, когда он действительно обновился. Это может быть в ситуациях, когда мы нажали на трек и произошло обновление истории поиска.

Одним из возможных решений является подписка на изменение данных в SharedPreference. В одном из уроков мы рассматривали, как можно добавить слушатель на изменение данных структуры в SharedPreference. 

Подобный подход в программировании называется "Реактивным". Это когда программа автоматически реагирует на изменения внешних источников данных, в том числе пользовательского ввода, сетевых запросов или изменений состояния системы, с помощью потоковых операций и реактивных потоков данных. Это обеспечивает более отзывчивый, масштабируемый и удобный в использовании код.

2023-04-21 18:15 UTC, NoDopezzz commented on app/src/main/java/com/practicum/playlistmaker/SearchActivity.kt
> +                deleteBtn.isGone = searchEditText.text.toString().trim().isEmpty()
💡 Для работы с `RecyclerView` существует очень хороший инструмент-помощник - `DiffUtils`. Он позволяет проверять текущий список `Recycler'а` и новый список, который мы хотим получить на схожесть. Он выделяет элементы, которые были изменены, добавлены или удалены и вызывает `notifyItem*` под каждый из них. Благодаря этому обновление списка происходит более оптимизировано, т.к. элементы изменяются точечно, а не все вместе, как это происходит с методом `notifyDataSetChanged()`.

Про то, как правильно готовить `DiffUtils` можно почитать вот [в этой статье](https://medium.com/android-news/smart-way-to-update-recyclerview-using-diffutil-345941a160e0)

2023-04-21 19:41 UTC, RomanKalin27 commented on app/src/main/java/com/practicum/playlistmaker/SearchActivity.kt
> +                if (searchEditText.hasFocus() && searchInput.isEmpty()) {
Исправил, пустого списка больше не должно быть. Остальное к следующему спринту подправлю.

2023-04-24 17:31 UTC, merged

2023-04-24 17:35 UTC, RomanKalin27 commented on app/src/main/java/com/practicum/playlistmaker/App.kt
> +    companion object {
Тогда тут пока ничего не меняю.

2023-04-24 17:38 UTC, RomanKalin27 commented on app/src/main/java/com/practicum/playlistmaker/App.kt
> +        }
Может я чего-то не понял, но у меня вроде все правильно работает. Там конечно можно добавить else, но это не должно ничего поменять.

2023-04-24 17:40 UTC, RomanKalin27 commented on app/src/main/java/com/practicum/playlistmaker/SearchActivity.kt
> +                deleteBtn.isGone = searchEditText.text.toString().trim().isEmpty()
Добавил diffutil, в итоге без них сделал. Избавился ото всех notify, от которых смог.

2023-04-24 17:41 UTC, RomanKalin27 commented on app/src/main/java/com/practicum/playlistmaker/SearchActivity.kt
> +                deleteBtn.isGone = searchEditText.text.toString().trim().isEmpty()
Остальное вроде все поправил.